# email_templates.py
from schemas import ODRequest

def render_od_email(payload: ODRequest, has_proof: bool, brand_hex: str = "#821238") -> tuple[str, str, str]:
    subject = f"OD Request • {payload.student.regno} • {payload.student.name}"

    text_body = (
        "Student\n"
        f"  Reg No : {payload.student.regno}\n"
        f"  Name   : {payload.student.name}\n"
        f"  Email  : {payload.student.email}\n"
        f"  Course : {payload.student.course}\n\n"
        "OD Details\n"
        f"  Event  : {payload.od.event}\n"
        f"  Date   : {payload.od.date}\n"
        f"  Proof  : {'attached' if has_proof else 'not attached'}\n"
    )

    # One brand strip (no text), one clear heading + subline
    html_body = f"""\
<!DOCTYPE html>
<html>
  <body style="margin:0;padding:0;background:#f6f6f6;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f6f6f6;">
      <tr><td align="center">
        <table role="presentation" width="600" cellpadding="0" cellspacing="0"
               style="width:600px;max-width:100%;background:#ffffff;border-radius:8px;overflow:hidden;border:1px solid #e5e5e5;">
          <tr>
            <td style="padding:0;background:{brand_hex};height:12px;line-height:12px;font-size:0;"></td>
          </tr>
          <tr><td style="padding:24px;font:14px/1.5 -apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;color:#333;">
            <h2 style="margin:0 0 6px;font-size:18px;color:{brand_hex};">
              OD Request — {payload.od.event}
            </h2>
            <p style="margin:0 0 16px;color:#666;font-size:13px;">
              {payload.student.name} · {payload.student.regno} · {payload.od.date}
            </p>

            <table role="presentation" cellpadding="6" cellspacing="0" style="width:100%;border-collapse:collapse">
              <tr><td style="width:140px;color:#555;">Reg No</td><td><strong>{payload.student.regno}</strong></td></tr>
              <tr><td style="color:#555;">Name</td><td>{payload.student.name}</td></tr>
              <tr><td style="color:#555;">Email</td><td>{payload.student.email}</td></tr>
              <tr><td style="color:#555;">Course</td><td>{payload.student.course}</td></tr>
            </table>

            <hr style="border:none;border-top:1px solid #eee;margin:16px 0" />

            <table role="presentation" cellpadding="6" cellspacing="0" style="width:100%;border-collapse:collapse">
              <tr><td style="width:140px;color:#555;">Event</td><td>{payload.od.event}</td></tr>
              <tr><td style="color:#555;">Date</td><td>{payload.od.date}</td></tr>
              <tr><td style="color:#555;">Proof</td><td>{'Attached' if has_proof else 'Not attached'}</td></tr>
            </table>
          </td></tr>

          <tr><td style="padding:14px 24px;background:#fafafa;color:#666;font:12px/1.4 -apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">
            Reply to this email to contact the student. This message was generated by the OD portal.
          </td></tr>
        </table>
      </td></tr>
    </table>
  </body>
</html>"""
    return subject, text_body, html_body
